name: gcdf-bri
channels:
  - conda-forge
dependencies:
  - python=3.11
  - geopandas>=0.14
  - pyogrio>=0.7
  - shapely>=2.0
  - fiona
  - pandas
  - numpy
  - streamlit>=1.34
  - folium>=0.15
  - branca
  - streamlit-folium>=0.18
  - geopy
  - rtree
  - pyproj
  - pip
  - pip:
      - mapclassify